from django.urls import path
from .import views

urlpatterns = [
path('dashboard/',views.dashboardview,name='dashboard'),
path('dashboard1/',views.dashboard1view,name='dashboard1'),
path('base_admin_dashboard/',views.base_admin_dashboardview,name='base_admin_dashboard'),
# path('base_operator_dashboard/',views.base_operator_dashboardview,name='base_operator_dashboard'),
# path('operator_dashboard/',views.dashboardoperatorview,name='operator_dashboard'),
# path('manager_dashboard/',views.dashboardmanagerview,name='manager_dashboard'),
# path('executive_dashboard/',views.dashboardexecutiveview,name='executive_dashboard'),
path('popup/',views.popupview,name='popup'),
path('po_info/',views.po_infoview,name='po_info'),
path('po_track/<str:po>',views.po_trackview,name='po_track'),
path('product_list/',views.product_listview,name='product_list'),
path('product_details/',views.product_details,name='product_details'),
path('asn_status/<str:id>/<str:pid>',views.asn_statusview,name='asn_status'),
path('cancel_order/<str:id>/<str:uid>',views.cancel_orderview,name='cancel_order'),
path('reject_status/<str:id>/<str:pid>',views.reject_statusview,name='reject_status'),
path('status_update/',views.status_updateview,name='status_update'),
path('order_list/',views.order_listview,name='order_list'),
path('acceptedlist/',views.acceptedlistview,name='acceptedlist'),
path('rejectedlist/',views.rejectedlistview,name='rejectedlist'),
path('mfg_orders/',views.mfg_orderview,name='mfg_orders'),
path('mfg_product/<str:id>',views.mfg_productview,name='mfg_product'),
path('mfg_order_details/',views.mfg_order_detailsview,name='mfg_order_details'),
path('dist_order_details/<str:po>',views.dist_order_detailsview,name='dist_order_details'),
path('consignment/',views.consignmentview,name='consignment'),
path('consign_details/<str:oid>',views.consign_detailsview,name='consign_details'),
path('conform_consign/',views.conform_consignview,name='conform_consign'),
# path('conform_consign/<str:oid>',views.conform_consignview,name='conform_consign'),
path('product_data/<str:gtin>',views.productdata,name='product_data'),
path('product_cart/<str:supplier_id>/<str:gtin>/<str:id>',views.product_cart,name='product_cart'),
path('cart/',views.cartview,name='cart'),
path('search_product/',views.search_product,name='search_product'),
path('order_conformed/<str:q>/<str:si>/<str:oi>/<str:uid>',views.order_conformed,name='order_conformed'),
# path('order_conformed/<str:q>/<str:si>/<str:oi>/<str:uid>',views.order_conformed,name='order_conformed'),
path('proceed_cart/',views.proceed_cart,name='proceed_cart'),
path('cart_checkout/<str:id>/<str:uid>',views.cart_checkout,name='cart_checkout'),
path('cart_address/<str:id>/<str:uid>',views.cart_address,name='cart_address'),
path('cartdata/<str:id>',views.cartdataview,name='cartdata'),
path('delete_cartitem/<str:cartid>/<str:uid>',views.delete_cartitem,name='delete_cartitem'),
# path('delete_cartitem/',views.delete_cartitem,name='delete_cartitem'),
path('order_list/',views.order_listview,name='order_list'),
path('order_details/',views.order_detailsview,name='order_details'),
path('checkout/',views.checkoutview,name='checkout'),
path('operatordashboard/',views.operatordashboard,name='operatordashboard'),
path('user_profile/',views.user_profileview,name='user_profile'),
path('approve_status/<str:id>',views.approve_status,name='approve_status'),
path('edit_status/<str:po>/<str:id>',views.edit_statusview,name='edit_status'),
path('delete_status/<str:id>',views.delete_status,name='delete_status'),
path('smart_contract/',views.smart_contract,name='smart_contract'),
path('smart_contract1/',views.smart_contractspost,name='smart_contract1'),
path('smart_contract_1/',views.smart_contract_1,name='smart_contract_1'),
path('smart_contracts/',views.smart_contracts,name='smart_contracts'),
path('smart_contract_3/',views.smart_contract_3,name='smart_contract_3'),
path('smart_contract_4/',views.smart_contract_4,name='smart_contract_4'),
path('manage_smart_contract/',views.manage_smart_contract,name='manage_smart_contract'),
# path('add_user_register/',views.add_userview,name='add_user'),
path('add_user/',views.add_userview,name='add_user'),
path('business_transactions/',views.business_transactions,name='business_transactions'),
path('business_transaction/',views.business_transaction,name='business_transaction'),
path('product_identify/',views.product_identify,name='product_identify'),
path('purchase_order/',views.purchase_order,name='purchase_order'),
path('transactiondata/',views.transactiondata,name='transactiondata'),
path('transaction_partners/<str:partner>',views.transaction_partners,name='transaction_partners'),
path('business_history/',views.business_history,name='business_history'),
# path('registerform_1/',views.registerform_idview,name='registerform_1'),
path('accounts/',views.accountsview,name='accounts'),
path('roles/',views.rolesview,name='roles'),
path('permissions/',views.permissionsview,name='permissions'),
path('licence/',views.licenceview,name='licence'),
path('manufacturer_order_details_edit/<int:id>',views.manufacturer_order_details_edit_view,name='manufacturer_order_details_edit'),
path('manufacturer_order_details/',views.manufacturer_order_details_view,name='manufacturer_order_details'),
# path('manufacturer_order_update/',views.manufacturer_order_update,name='manufacturer_order_update'),
# path('distributor_order_details_edit/<int:id>',views.distributor_order_details_edit_view,name='distributor_order_details_edit'),
# path('distributor_order_details/',views.distributor_order_details_view,name='distributor_order_details'),
# path('distributor_order_update/',views.distributor_order_update,name='distributor_order_update'),
# path('retailer_order_details1/',views.retailer_order_details_view,name='retailer_order_details1'),
# path('retailer_order_update/',views.retailer_order_update,name='retailer_order_update'),

# path('logistics_order_details_edit/<int:id>',views.logistics_order_details_edit_view,name='logistics_order_details_edit'),
# path('logistics_order_details/',views.logistics_order_details_view,name='logistics_order_details'),
# path('logistics_order_update/',views.logistics_order_update,name='logistics_order_update'),

# path('retailer_order_details_edit/<int:id>',views.retailer_order_details_edit_view,name='retailer_order_details_edit'),
# path('retailer_order_details/',views.retailer_order_details_view,name='retailer_order_details'),
# path('retailer_order_update/',views.retailer_order_update,name='retailer_order_update'),

path('tracknew/<str:ssccid>',views.tracknewview,name='tracknew'),
# path('tracknew/<str:id>/<str:ssccid>',views.tracknewview,name='tracknew'),
path('distrack/<str:id>/<str:serialid>',views.distrackview,name='distrack'),
# path('distrack/<str:id>/<str:searchInput>/<str:serialid>',views.distrackview,name='distrack'),
path('tracenew/<str:id>',views.tracenewview,name='tracenew'),
path('tracenew/<str:id>/<str:searchInput>/<str:serialid>',views.tracenewview,name='tracenew'),
path('delete/<str:id>',views.delete,name='delete'),
# path('updateuser/<str:id>',views.updateuser,name='updateuser'),
path('test/',views.testview,name='test'),
path('Track&Trace/',views.TrackTraceview,name='Track&Trace'),
path('product_publish/',views.product_publish,name='product_publish'),
path('tracktrace/',views.tracktrace,name='tracktrace'),
path('mainbase/',views.mainbaseview,name='mainbase'),

path('qrcodes/',views.qrcodes,name='qrcodes'),

path('productmasterdata/',views.productmasterdataview,name='productmasterdata'),



# path('show',views.show,name='show'),
# path('search/',views.search,name='search'),
path('sscc_info/',views.sscc_info,name='sscc_info'),
path('searchlevel/',views.searchlevel,name='searchlevel'),
# path('searchresult/',views.searchresultview,name='searchresult'),
# path('searchunitlevel/',views.searchunitlevelview,name='searchunitlevel'),
# path('searchcaselevel/',views.searchcaselevelview,name='searchcaselevel'),
# path('tracenew/',views.retailertraceview,name='tracenew'),
path('retailtrace/',views.retailtraceview,name='retailtrace'),
# path('distributortrace/',views.distributortraceview,name='distributortrace'),
path('distribtrace/',views.distribtraceview,name='distribtrace'),

path('transactionform',views.transactionformview,name='transactionform'),
# path('verification/',views.verification,name='verification'),
path('verify/',views.verifyview,name='verify'),
# path('trace_identification/',views.trace_identification,name='trace_identification'),

# path('retailer_identification/',views.retailer_identification,name='retailer_identification'),

# path('distributor_identification/',views.distributor_identification,name='distributor_identification'),

# path('lsp_identification/',views.lsp_identification,name='lsp_identification'),
path('base/',views.base_view,name='base'),
path('error/',views.error_view,name='error'),
path('error1/',views.error1_view,name='error1'),
path('error2/',views.error2_view,name='error2'),
path('home/',views.homeview,name='home'),
# path('registerform1/',views.registerform1_view,name='registerform1'),
path('details/',views.detailsview,name='details'),
path('',views.loginview,name='login'),
path('logout',views.logoutview,name='logout'),
path('Reset-password/',views.resetpasswordview,name='Reset-password'),
path('Forgot-password/',views.forgotpasswordview,name='forgot-password'),
# path('Register-form-1/',views.registerform1view,name='Register-form-1'),
path('register/',views.registerview,name='register'),
# path('bulk_insert/',views.simple_upload,name='bulk_insert'),
# path('Registration-form-2/',views.registerform2view,name='Registration-form-2'),
path('Reset-password/',views.reset_password,name='Reset-password'),
]
